import React, { useState } from "react";
import useStore from "../../useStore";
import JSZip from "jszip";

// Import your styles
import "../HeaderStep/HeaderStep.css"; 
import "../HeroStep/HeroStep.css";
import "../StoreStep/StoreStep.css"; 
import "../FooterStep/FooterStep.css";

function FinalPreview() {
  const data = useStore((state) => state.data);
  const [isDownloading, setIsDownloading] = useState(false);

  // Extract all Zustand data, including the missing Contact Step details
  const {
    headerBgColor = "#ffffff",
    headerBorderColor = "",
    headerHeight = "",
    headerLogoWidth = 100,
    headerLogo = "",
    navLinkColor = "#444",
    heroBgColor = "#ffffff",
    heroBorderColor = "",
    titleFont = "Arial",
    heroTitleColor = "#1f2937",
    heroTitle = "Your hero",
    subtitleFont = "Arial",
    subheroTitleColor = "#4f46e5",
    heroSubtitle = "Your hero subtitle",
    paragraphFont = "Arial",
    descColor = "#4b5563",
    heroDescription = "your hero description.",
    heroBtnColor = "#6366f1",
    heroBtnTextColor = "#ffffff",
    currentImage = "",
    heroImgWidth = 100,
    products = [],
    whatsapp = "",
    instagram = "",
    email = "",
    footerBgColor = "#ffffff",
    footerTextColor = "#4b5563",
    footerTitleColor = "#1f2937",
    brandName = "UrStore",
    brandDesc = "Build your dream store with zero code.",
    copyrightText = "All rights reserved."
  } = data;

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const zip = new JSZip();
      const imgFolder = zip.folder("images");

      // Helper function to fetch Blob URLs from memory and save them to the ZIP
      const processImage = async (url: string, name: string) => {
        if (!url) return "";
        // If it's a standard web URL (not a local blob generated by URL.createObjectURL), just return it
        if (url.startsWith('http') && !url.startsWith('blob:')) return url; 
        
        try {
          const res = await fetch(url);
          const blob = await res.blob();
          imgFolder?.file(name, blob); // Save physical file in the 'images' folder
          return `./images/${name}`; // Return the relative path for the HTML file
        } catch (error) { 
          console.error("Error processing image:", error);
          return ""; 
        }
      };

      // Process all images
      const headerPath = await processImage(headerLogo, "logo.png");
      const heroPath = await processImage(currentImage, "hero.png");
      const processedProducts = await Promise.all(
        products.map(async (p: any, i: number) => ({
          ...p,
          localPath: await processImage(p.imageUrl, `product-${i}.png`)
        }))
      );

      // Build the contact links dynamically based on what the user provided
      let socialLinksHtml = '';
      if (whatsapp) socialLinksHtml += `<a href="https://wa.me/${whatsapp.replace(/[^0-9]/g, '')}" class="contact-btn whatsapp">WhatsApp</a>`;
      if (instagram) socialLinksHtml += `<a href="https://instagram.com/${instagram.replace('@', '')}" class="contact-btn instagram">Instagram</a>`;
      if (email) socialLinksHtml += `<a href="mailto:${email}" class="contact-btn email">Email</a>`;

      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${brandName}</title>
    <style>
        html { scroll-behavior: smooth; }
        body { margin: 0; padding: 0; font-family: ${paragraphFont}, sans-serif; overflow-x: hidden; }
        * { box-sizing: border-box; }
        
        /* HEADER */
        header { 
            display: flex; justify-content: space-between; align-items: center; 
            padding: 0 5%; background: ${headerBgColor}; 
            border-bottom: ${headerBorderColor ? `2px solid ${headerBorderColor}` : 'none'};
            height: ${headerHeight ? `${headerHeight}px` : '80px'};
            position: sticky; top: 0; z-index: 1000;
        }
        header img { height: ${headerLogoWidth}px; }
        header nav ul { display: flex; list-style: none; gap: 30px; margin: 0; }
        header nav a { text-decoration: none; color: ${navLinkColor}; font-weight: bold; transition: opacity 0.2s; }
        header nav a:hover { opacity: 0.7; }

        /* HERO */
        #home { 
            display: flex; align-items: center; min-height: 80vh; padding: 60px 5%; 
            background: ${heroBgColor}; flex-wrap: wrap;
            border-bottom: ${heroBorderColor ? `2px solid ${heroBorderColor}` : 'none'};
        }
        .hero-text { flex: 1; min-width: 300px; }
        .hero-text h1 { font-family: ${titleFont}; color: ${heroTitleColor}; font-size: 3.5rem; margin: 0; }
        .hero-text h2 { font-family: ${subtitleFont}; color: ${subheroTitleColor}; font-size: 1.8rem; }
        .hero-text p { color: ${descColor}; font-size: 1.1rem; line-height: 1.6; max-width: 600px; }
        .hero-btn { 
            background: ${heroBtnColor}; color: ${heroBtnTextColor}; 
            padding: 15px 35px; border: none; border-radius: 50px; 
            font-size: 1.1rem; font-weight: bold; cursor: pointer; margin-top: 20px;
        }
        .hero-img { flex: 1; display: flex; justify-content: center; }
        .hero-img img { width: ${heroImgWidth}%; border-radius: 20px; }

        /* STORE */
        #store { padding: 80px 5%; background: #ffffff; }
        .store-grid { 
            display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); 
            gap: 40px; margin-top: 50px; 
        }
        .card { background: white; border-radius: 15px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.05); transition: 0.3s; }
        .card:hover { transform: translateY(-10px); }
        .card img { width: 100%; height: 250px; object-fit: cover; }
        .card-body { padding: 20px; text-align: center; }
        .card-body h3 { margin: 0; font-size: 1.3rem; }
        .price { color: #6366f1; font-weight: bold; font-size: 1.2rem; margin-top: 10px; }

        /* CONTACT LINKS */
        .contact-links { display: flex; gap: 15px; justify-content: center; margin-top: 20px; }
        .contact-btn { padding: 10px 20px; border-radius: 8px; text-decoration: none; color: white; font-weight: bold; }
        .whatsapp { background-color: #25D366; }
        .instagram { background: linear-gradient(45deg, #f09433, #e6683c, #dc2743, #cc2366, #bc1888); }
        .email { background-color: #4b5563; }

        /* FOOTER */
        footer { padding: 60px 5%; background: ${footerBgColor}; color: ${footerTextColor}; text-align: center;}
        .footer-brand h2 { color: ${footerTitleColor}; margin: 0; }
    </style>
</head>
<body>
    <header>
        ${headerPath ? `<img src="${headerPath}" alt="Logo">` : `<h2>${brandName}</h2>`}
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#store">Store</a></li>
            </ul>
        </nav>
    </header>

    <section id="home">
        <div class="hero-text">
            <h1>${heroTitle}</h1>
            <h2>${heroSubtitle}</h2>
            <p>${heroDescription}</p>
            <button class="hero-btn" onclick="location.href='#store'">Shop Now</button>
        </div>
        <div class="hero-img">
            ${heroPath ? `<img src="${heroPath}" alt="Hero Image">` : ''}
        </div>
    </section>

    <section id="store">
        <h2 style="font-size: 2.5rem; text-align: center;">Our Products</h2>
        <div class="store-grid">
            ${processedProducts.map(p => `
                <div class="card">
                    <img src="${p.localPath}" alt="${p.name}">
                    <div class="card-body">
                        <h3>${p.name}</h3>
                        <div class="price">${p.price} MAD</div>
                    </div>
                </div>
            `).join('')}
        </div>
    </section>

    <footer>
        <div class="footer-brand">
            <h2>${brandName}</h2>
            <p>${brandDesc}</p>
        </div>
        
        ${socialLinksHtml ? `<div class="contact-links">${socialLinksHtml}</div>` : ''}
        
        <hr style="opacity: 0.1; margin: 40px 0;">
        <p>&copy; ${new Date().getFullYear()} ${brandName}. ${copyrightText}</p>
    </footer>
</body>
</html>`;

      // Add HTML to ZIP
      zip.file("index.html", htmlContent);
      
      // Generate the ZIP file blob
      const content = await zip.generateAsync({ type: "blob" });
      
      // Trigger the download automatically
      const link = document.createElement("a");
      link.href = URL.createObjectURL(content);
      link.download = `${brandName.toLowerCase().replace(/\s+/g, '-')}-store.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      // Clean up the object URL to free memory
      URL.revokeObjectURL(link.href);

    } catch (error) {
      console.error("Failed to generate ZIP:", error);
      alert("Something went wrong while generating your store.");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div style={{ backgroundColor: "#f1f5f9", minHeight: "100vh" }}>
      {/* BUILDER ACTION BAR */}
      <div style={{ padding: "20px 5%", display: "flex", justifyContent: "space-between", alignItems: "center", background: "#fff", borderBottom: "1px solid #e2e8f0" }}>
        <h2 style={{ margin: 0, color: "#1e293b" }}>Store Final Preview</h2>
        
        {/* THE DOWNLOAD BUTTON */}
        <button 
          onClick={handleDownload}
          disabled={isDownloading}
          style={{ 
            padding: "12px 25px", 
            background: isDownloading ? "#94a3b8" : "#10b981", 
            color: "#fff", 
            border: "none", 
            borderRadius: "8px", 
            fontWeight: "bold", 
            cursor: isDownloading ? "not-allowed" : "pointer",
            transition: "background 0.3s ease"
          }}
        >
          {isDownloading ? "Zipping your store..." : "Download Store (ZIP)"}
        </button>
      </div>

      {/* LIVE PREVIEW AREA */}
      <div style={{ background: "#fff", width: "100%", overflowX: "hidden" }}>
        <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0 5%", background: headerBgColor, height: headerHeight ? `${headerHeight}px` : "80px", borderBottom: headerBorderColor ? `2px solid ${headerBorderColor}` : "none" }}>
          {headerLogo ? <img src={headerLogo} style={{ height: `${headerLogoWidth}px` }} alt="logo" /> : <h2 style={{margin: 0}}>{brandName}</h2>}
          <ul style={{ display: "flex", listStyle: "none", gap: "30px", margin: 0 }}>
            <li><a href="#home" style={{ color: navLinkColor, textDecoration: "none", fontWeight: "bold" }}>Home</a></li>
            <li><a href="#store" style={{ color: navLinkColor, textDecoration: "none", fontWeight: "bold" }}>Store</a></li>
          </ul>
        </header>

        <section id="home" style={{ display: "flex", alignItems: "center", padding: "80px 5%", background: heroBgColor, flexWrap: "wrap", borderBottom: heroBorderColor ? `2px solid ${heroBorderColor}` : "none" }}>
          <div style={{ flex: 1, minWidth: "300px" }}>
            <h1 style={{ fontFamily: titleFont, color: heroTitleColor, fontSize: "3.5rem", margin: 0 }}>{heroTitle}</h1>
            <h2 style={{ fontFamily: subtitleFont, color: subheroTitleColor, fontSize: "1.8rem", margin: "10px 0" }}>{heroSubtitle}</h2>
            <p style={{ fontFamily: paragraphFont, color: descColor, fontSize: "1.1rem", marginBottom: "30px" }}>{heroDescription}</p>
            <button style={{ background: heroBtnColor, color: heroBtnTextColor, padding: "15px 35px", border: "none", borderRadius: "50px", cursor: "pointer", fontWeight: "bold" }}>Shop Now</button>
          </div>
          <div style={{ flex: 1, display: "flex", justifyContent: "center" }}>
            {currentImage && <img src={currentImage} style={{ width: `${heroImgWidth}%`, borderRadius: "20px" }} alt="hero" />}
          </div>
        </section>

        <section id="store" style={{ padding: "80px 5%" }}>
          <h2 style={{ textAlign: "center", fontSize: "2.5rem", marginBottom: "40px" }}>Our Products</h2>
          <div className="products-grid">
            {products.map((p: any) => (
              <div key={p.id} className="product-card">
                <img src={p.imageUrl} alt={p.name} style={{ width: "100%", height: "250px", objectFit: "cover", borderTopLeftRadius: "15px", borderTopRightRadius: "15px" }} />
                <div className="product-info" style={{ padding: "20px", textAlign: "center" }}>
                  <h3 style={{ margin: 0 }}>{p.name}</h3>
                  <div className="price-tag" style={{ color: "#6366f1", fontWeight: "bold", marginTop: "10px", fontSize: "1.2rem" }}>{p.price} MAD</div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <footer style={{ padding: "60px 5%", background: footerBgColor, color: footerTextColor, textAlign: "center" }}>
          <h2 style={{ color: footerTitleColor, margin: "0 0 10px 0" }}>{brandName}</h2>
          <p style={{ margin: "0 0 30px 0" }}>{brandDesc}</p>
          
          <div style={{ display: "flex", gap: "15px", justifyContent: "center", marginBottom: "30px" }}>
             {whatsapp && <button style={{ padding: "10px 20px", background: "#25D366", color: "white", border: "none", borderRadius: "8px", fontWeight: "bold" }}>WhatsApp</button>}
             {instagram && <button style={{ padding: "10px 20px", background: "#E1306C", color: "white", border: "none", borderRadius: "8px", fontWeight: "bold" }}>Instagram</button>}
             {email && <button style={{ padding: "10px 20px", background: "#4b5563", color: "white", border: "none", borderRadius: "8px", fontWeight: "bold" }}>Email</button>}
          </div>

          <hr style={{ opacity: 0.2 }} />
          <p style={{ marginTop: "20px" }}>&copy; {brandName} {copyrightText}</p>
        </footer>
      </div>
    </div>
  );
}

export default FinalPreview;